### PR TITLE
update py, md for #32

### PR DESCRIPTION
**Pull request by Yuya670**
update mitre_attack_csv.py and README.md for Add ATT&CK version numbers to the CSV files(#32)

### CODE REVIEW

**Review by stmtstk — COMMENTED** [review]
We got some errors from super_linter.

```
/github/workspace/README.md:9:401 MD013/line-length Line length [Expected: 400; Actual: 443]
[156](https://github.com/stmtstk/mitre_attack_csv/runs/8137860233?check_suite_focus=true#step:4:157)
/github/workspace/README.md:51:34 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 3]
[157](https://github.com/stmtstk/mitre_attack_csv/runs/8137860233?check_suite_focus=true#step:4:158)
/github/workspace/README.md:52:1 MD034/no-bare-urls Bare URL used [Context: "https://attack.mitre.org/resou..."]
```

These errors are not caused by this fix. However, We should discuss whether super_linter should be configured to ignore these errors.

**Review by stmtstk — CHANGES_REQUESTED** [review]
@Yuya670 
Could you replace the 3 spaces on line 51 of README.md with 2 spaces?

Before
`This project makes use of ATT&CK®   `

After
`This project makes use of ATT&CK®  `

**Review by stmtstk — CHANGES_REQUESTED** [review]
Also, is it possible to replace the last URL in the "README.md" and not generate the auto-anchor?

Before
`https://attack.mitre.org/resources/terms-of-use/`

After
`https&#58;//attack.mitre.org/resources/terms-of-use/`

**Comment by rmasuoka** [comment]
I am good with Readme.md and mitre-attack-csv.ph.

**Review by stmtstk — APPROVED** [review]
@rmasuoka  Thanks.

**Comment by rmasuoka** [comment]
@Yuya670 Could you also replace the CSV files with ones with version numbers in the repository?

**Review by stmtstk — COMMENTED** [review]
@Yuya670 

Could you insert a new line on `README.md` line 9?

`super_linter` notices, this line is too long.

We should break the line like below.
```
The script (mitre_attack_csv.py) extracts all types of SDOs (STIX Domain Objects) and SROs (STIX Relationship Objects), including STIX extensions, from the latest or the specified version of ATT&CK STIX JSON file and converts and saves them into CSV files for each SDO type and one for SRO. 
You can find the resulting CSV files for the different versions of ATT&CK in the "attack-csv" directory. You can give following arguments to the script.
```

**Review by stmtstk — APPROVED** [review]

**Pull request merged**
