### PR TITLE
Update mitre_attack_csv.py

### PR DESCRIPTION
**Pull request by rmasuoka**
Dealt with Issues #1 and #2
Decided to go with --id instead of -mitre-attack-id for tardiness

### CODE REVIEW

**Comment by rmasuoka** [comment]
PR の Chat とはこれのことかしら?

**Comment by shinsugarfj** [comment]
@rmasuoka ですです

**Review by shiracamus — APPROVED** [review]
I have reviewed it and it is fine.

**Comment by rmasuoka** [comment]
Thanks, Shinji and Kazu!

**Review by stmtstk — CHANGES_REQUESTED** [review]
Please remove `.gitignore` file.
`.DS_store` should not be included in `.gitignore` because some contributors do not use MacOS.
`.DS_Store` should be ignored in each git environment.

**Comment by rmasuoka** [comment]
How about --attack-id, --attack-version?

**Comment by stmtstk** [comment]
> How about --attack-id, --attack-version?

I am sure these options are suitable.

**Comment by rmasuoka** [comment]
I guess I need to change them to --attack_id, --attack_version so that I can use options.attack_id, options.attack_version in Python

**Review by stmtstk — CHANGES_REQUESTED** [review]
Please remove `.DS_Store`

**Comment by rmasuoka** [comment]
@stmtstk I believe it is ready.

**Comment by stmtstk** [comment]
@rmasuoka @shiracamus @shinsugarfj Thank you, all!

**Pull request merged**
