### PR TITLE
enhance: add a script to create index.html files of CSV file links for github.io

### PR DESCRIPTION
**Pull request by shiracamus**

### CODE REVIEW

**Review by stmtstk — COMMENTED** [review]
I checked this shell from a shell script perspective. It seems to be good.
We should check the html files generated by this script from a design perspective.

**Comment by rmasuoka** [comment]
@shiracamus Why don't we combine this with [produce-all-attack-csv-files.sh](https://github.com/stmtstk/mitre_attack_csv/blob/main/produce-all-attack-csv-files.sh) to create "produce-attack-csv-data-storage.sh"?

**Comment by shiracamus** [comment]
@ryu I made it a separate file because of the different functionality.
I think it is better to combine them in a script named deploy.sh or to call both scripts from deploy.sh.

**Comment by rmasuoka** [comment]
Okay, I am good then.

**Review by rmasuoka — APPROVED** [review]

**Comment by rmasuoka** [comment]
I have approved the change.

**Comment by stmtstk** [comment]
Thanks for your contribution.

**Pull request merged**
