### PR TITLE
Created all CSV files in the attack-csv folder

### PR DESCRIPTION
**Pull request by rmasuoka**
Hopefully, this is my last PR.
Removed the output folder and created all CSV files (with or without mitre-attack-id) for all available versions of ATT&CK in the attack-csv folder

### CODE REVIEW

**Comment by shiracamus** [comment]
私は、リポジトリにcsvファイルを含めない方がいいと思います。
csvブランチを作ってcsvファイルを格納するのはどうでしょうか？

**Comment by shiracamus** [comment]
よくみたら、outputディレクトリもありますね。
これは削除した方がいいし、.gitignore に output と attack.json を書いて置いておくのがいいですね。

**Comment by rmasuoka** [comment]
@shiracamus Making those CSV files available on the Internet is the whole point of this effort (at least for me). Something like [MITRE ATT&CK](https://github.com/mitre-attack/attack-stix-data/blob/master/index.md). How does your "How about creating a attack_csv branch to store the csv files?" work? Are CSV files going to be easily accessible?

**Comment by rmasuoka** [comment]
@shiracamus By the way, I have removed "output" folder in this PR.

**Comment by rmasuoka** [comment]
@shiracamus The change (remove the "output" folder) appears at the end of "Files changed" tab.

**Comment by shiracamus** [comment]
@rmasuoka I understand your point.
Even if you create a branch, you can easily access the files.
Also, I think it would be more convenient to separate directories for files with ids, what do you think?

**Review by stmtstk — COMMENTED** [review]
@rmasuoka 

I am not sure that `produce-all-attack-csvs.sh` is appropriate or not.
`produce-all-atack-csv-files.sh` is more accurate representation.

**Comment by rmasuoka** [comment]
Agreed. I have changed the shell script name and committed the change.

**Review by stmtstk — APPROVED** [review]

**Pull request merged**
