### PR TITLE
add version option

### PR DESCRIPTION
**Pull request by Yuya670**
add argparce --version and -V to get Tool version

### CODE REVIEW

**Comment by rmasuoka** [comment]
Why don't you use "1.0" for its version number? I think it is quite ready. (Does anyone have anything else to add/remove to/from the script?)

**Review by rmasuoka — APPROVED** [review]
I am good with this change. Thank you, Yuya!

**Review by stmtstk — CHANGES_REQUESTED** [review]
＠Yuya670 Thanks for your contribution. Please use `1.0.0` for TOOL_VERSION instead of `0.0`.
Commit the change and push the 'Output-tool-version-information' again.

**Comment by Yuya670** [comment]
I change value of TOOL_VERSION and push. 
Please review again.
Thank you.

**Review by stmtstk — APPROVED** [review]

**Comment by stmtstk** [comment]
This pull request was resolved in #14, so will be closed.

**Pull request closed without merging**
